import type { Match } from "@/types";

export const MATCHES: Match[] = [
  { id: 1, home: "MEXICO", away: "SUDAFRICA" },
  { id: 2, home: "COREA DEL SUR", away: "REPUBLICA CHECA" },
  { id: 3, home: "BOSNIA Y HERZEGOVINA", away: "EGIPTO" },
  { id: 4, home: "ESTADOS UNIDOS", away: "PARAGUAY" },
  { id: 5, home: "SUIZA", away: "QATAR" },
  { id: 6, home: "BRASIL", away: "MARRUECOS" },
  { id: 7, home: "HAITI", away: "ESCOCIA" },
  { id: 8, home: "AUSTRALIA", away: "TURQUIA" },
  { id: 9, home: "ALEMANIA", away: "CURAZAO" },
  { id: 10, home: "PAISES BAJOS", away: "JAPON" },
  { id: 11, home: "COSTA DE MARFIL", away: "ECUADOR" },
  { id: 12, home: "SUECIA", away: "TUNEZ" },
  { id: 13, home: "ESPAÑA", away: "REPUBLICA CHECA" },
  { id: 14, home: "COREA DEL SUR", away: "SUDAFRICA" },
  { id: 15, home: "CANADA", away: "ARABIA SAUDI" },
  { id: 16, home: "BELGICA", away: "IRAN" },
  { id: 17, home: "FRANCIA", away: "NUEVA ZELANDA" },
  { id: 18, home: "IRAK", away: "NORUEGA" },
  { id: 19, home: "MARRUECOS", away: "ARGENTINA" },
  { id: 20, home: "AUSTRIA", away: "JORDANIA" },
  { id: 21, home: "PORTUGAL", away: "RD DEL CONGO" },
  { id: 22, home: "INGLATERRA", away: "CROACIA" },
  { id: 23, home: "PANAMA", away: "GHANA" },
  { id: 24, home: "UZBEKISTAN", away: "COLOMBIA" },
  { id: 25, home: "ESPAÑA", away: "SUDAFRICA" },
  { id: 26, home: "BOSNIA Y HERZEGOVINA", away: "BELGICA" },
  { id: 27, home: "CANADA", away: "URUGUAY" },
  { id: 28, home: "MEXICO", away: "COREA DEL SUR" },
  { id: 29, home: "SENEGAL", away: "ESTADOS UNIDOS" },
  { id: 30, home: "ESCOCIA", away: "FRANCIA" },
  { id: 31, home: "BRASIL", away: "HAITI" },
  { id: 32, home: "TURQUIA", away: "PARAGUAY" },
  { id: 33, home: "PAISES BAJOS", away: "PORTUGAL" },
  { id: 34, home: "ALEMANIA", away: "INGLATERRA" },
  { id: 35, home: "ECUADOR", away: "PANAMA" },
  { id: 36, home: "TUNEZ", away: "JAPON" },
  { id: 37, home: "CABO VERDE", away: "ARABIA SAUDI" },
  { id: 38, home: "BELGICA", away: "IRAN" },
  { id: 39, home: "URUGUAY", away: "QATAR" },
  { id: 40, home: "NUEVA ZELANDA", away: "EGIPTO" },
  { id: 41, home: "AUSTRALIA", away: "AUSTRIA" },
  { id: 42, home: "MARRUECOS", away: "IRAK" },
  { id: 43, home: "BRASIL", away: "NORUEGA" },
  { id: 44, home: "JORDANIA", away: "ARGELIA" },
  { id: 45, home: "PAISES BAJOS", away: "SUECIA" },
  { id: 46, home: "INGLATERRA", away: "GHANA" },
  { id: 47, home: "CURAZAO", away: "CROACIA" },
  { id: 48, home: "COLOMBIA", away: "RD DEL CONGO" },
  { id: 49, home: "SUIZA", away: "CANADA" },
  { id: 50, home: "BOSNIA Y HERZEGOVINA", away: "QATAR" },
  { id: 51, home: "MARRUECOS", away: "HAITI" },
  { id: 52, home: "ESCOCIA", away: "BRASIL" },
  { id: 53, home: "SUDAFRICA", away: "COREA DEL SUR" },
  { id: 54, home: "REPUBLICA CHECA", away: "MEXICO" },
  { id: 55, home: "NUEVA ZELANDA", away: "BELGICA" },
  { id: 56, home: "IRAN", away: "CURAZAO" },
  { id: 57, home: "ECUADOR", away: "ALEMANIA" },
  { id: 58, home: "TUNEZ", away: "PAISES BAJOS" },
  { id: 59, home: "JAPON", away: "SUECIA" },
  { id: 60, home: "TURQUIA", away: "ESTADOS UNIDOS" },
  { id: 61, home: "NORUEGA", away: "FRANCIA" },
  { id: 62, home: "SENEGAL", away: "IRAK" },
  { id: 63, home: "CABO VERDE", away: "ARABIA SAUDI" },
  { id: 64, home: "URUGUAY", away: "ESPAÑA" },
  { id: 65, home: "EGIPTO", away: "BOSNIA Y HERZEGOVINA" },
  { id: 66, home: "ESTADOS UNIDOS", away: "ARGENTINA" },
  { id: 67, home: "PANAMA", away: "COSTA DE MARFIL" },
  { id: 68, home: "CROACIA", away: "GHANA" },
  { id: 69, home: "PORTUGAL", away: "COLOMBIA" },
  { id: 70, home: "RD DEL CONGO", away: "UZBEKISTAN" },
  { id: 71, home: "ARGELIA", away: "AUSTRIA" },
  { id: 72, home: "JORDANIA", away: "ARGENTINA" },
];
